---
sshd_templates_directory: "{{ role_path }}/templates"

sshd_user_uid: "0"
sshd_user_gid: "0"

sshd_config_port: "22"
sshd_config_address_family: "any"
sshd_config_listen_addresses:
  - "0.0.0.0"
  - "::"
sshd_config_host_keys:
  - "/etc/ssh/ssh_host_rsa_key"
  - "/etc/ssh/ssh_host_ecdsa_key"
  - "/etc/ssh/ssh_host_ed25519_key"
sshd_config_rekey_limit: "default none"
sshd_config_syslog_facility: "AUTH"
sshd_config_log_level: "INFO"
sshd_config_login_grace_time: "2m"
sshd_config_permit_root_login: "prohibit-password"
sshd_config_strict_modes: "yes"
sshd_config_max_auth_tries: "6"
sshd_config_max_sessions: "10"
sshd_config_pubkey_authentication: "yes"
sshd_config_keys_file: ".ssh/authorized_keys .ssh/authorized_keys2"
sshd_config_principals_file: "none"
sshd_config_authorized_keys_command: "none"
sshd_config_authorized_keys_command_user: "nobody"
sshd_config_host_based_authentication: "no"
sshd_config_ignore_user_known_hosts: "no"
sshd_config_ignore_rhosts: "yes"
sshd_config_password_authentication: "yes"
sshd_config_permit_empty_passwords: "no"
sshd_config_challenge_response_authentication: "no"
sshd_config_kerberos_authentication: "no"
sshd_config_kerberos_or_local_passwd: "yes"
sshd_config_kerberos_ticket_cleanup: "yes"
sshd_config_kerberos_get_afs_token: "no"
sshd_config_gssapi_authentication: "no"
sshd_config_gssapi_cleanup_credentials: "yes"
sshd_config_gssapi_strict_acceptor_check: "yes"
sshd_config_gssapi_key_exchange: "no"
sshd_config_use_pam: "yes"
sshd_config_allow_agent_forwarding: "yes"
sshd_config_allow_tcp_forwarding: "yes"
sshd_config_gateway_ports: "no"
sshd_config_x11_forwarding: "yes"
sshd_config_x11_display_offset: "10"
sshd_config_x11_use_localhost: "yes"
sshd_config_permit_tty: "yes"
sshd_config_print_motd: "no"
sshd_config_print_last_log: "yes"
sshd_config_tcp_keep_alive: "yes"
sshd_config_permit_user_environment: "no"
sshd_config_compression: "delayed"
sshd_config_client_alive_interval: "0"
sshd_config_client_alive_count_max: "3"
sshd_config_use_dns: "no"
sshd_config_pid_file: "/var/run/sshd.pid"
sshd_config_max_startups: "10:30:100"
sshd_config_permit_tunnel: "no"
sshd_config_chroot_directory: "none"
sshd_config_version_addendum: "none"
sshd_config_banner: "none"
sshd_config_accept_env: "LANG LC_*"
sshd_config_sub_system: "sftp /usr/lib/openssh/sftp-server"
