---
- name: Configure base system
  hosts: factory_servers
  gather_facts: "yes"
  become: "yes"
  become_method: "su"
  pre_tasks:
    - name: Handle users
      ansible.builtin.include_tasks: "tasks/users.yaml"
  roles:
    - role: apt
    - role: profile
      vars:
        profile_hostname: "{{ default_hostname }}"
        profile_entries:
          - uid: "{{ default_user_uid }}"
            gid: "{{ default_user_gid }}"
            home: "{{ default_user_home }}"
    - role: sudo
      vars:
        sudo_user: "{{ default_user_name }}"
    - role: sshd
